version: '3.7'

services:
  nginx:
    hostname: nginx

    image: ymuski/nginx-quic
    volumes:
      - ./certs:/opt/nginx/certs/
      - ./cert:/opt/nginx/cert/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "80:80"
    network_mode: bridge

  curl:
    hostname: curl
    image: ymuski/curl-http3
    links:
      - nginx
    network_mode: bridge
    command: ["curl", "-ILv", "https://172.17.0.2", "--http3"]