version: '3.3'

services:
  quic-server:
    container_name: quic
    image: node:staging
    ports:
      - "1234:1234/udp"
      - "1234:1234/tcp"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - ./package.json:/package.json
      - ./traffic/:/traffic/
      - ./quic/:/quic/
      - ./tcp/:/tcp/
  tcp-server:
    container_name: tcp
    image: node:staging
    ports:
      - "1337:1337/tcp"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - ./package.json:/package.json
      - ./traffic/:/traffic/
      - ./quic/:/quic/
      - ./tcp/:/tcp/
