version: '3.3'

services:
  quic-server:
    container_name: qnode
    image: node:staging
    ports:
      - "1234:1234/udp"
      - "1234:1234/tcp"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/package.json:/package.json
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/run_server_client.py:/run_server_client.py
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/traffic/:/traffic/
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/quic/:/quic/
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/tcp/:/tcp/
  quic-client:
    container_name: qnode2
    image: node:staging
    ports:
      - "1337:1337/tcp"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/package.json:/package.json
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/run_server_client.py:/run_server_client.py
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/traffic/:/traffic/
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/quic/:/quic/
      - /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/tcp/:/tcp/




  #   image: ws2018sacc/experimentalnodejs
  #   network_mode: host
  #   build:
  #     context: ../quic-benchmark
  #     dockerfile: /Users/jonathanl./Documents/Studium/Master/Semester05/KP-RN/quic-benchmark/Dockerfile
  #   ports:
  #     - 7788:7788
  # quic-client:
  #   network_mode: host
  #   image: ws2018sacc/experimentalnodejs
  #   build:
  #     context: ../quic-benchmark
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 7789:7789