version: '3.7'

services:
  nginx:
    hostname: nginx

    image: ymuski/nginx-quic
    volumes:
      - ./certs:/opt/nginx/certs/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "80:80"
    network_mode: bridge

  curl-http3:
    hostname: curl-http3
    image: ymuski/curl-http3
    links:
      - nginx
    network_mode: bridge
    command: ["sleep", "200"]
    # command: ["curl", "-ILv", "https://nginx", "--http3"]

  curl-http2:
    hostname: curl-http2
    image: curlimages/curl
    links:
      - nginx
    network_mode: bridge
    command: ["sleep", "200"]
    # command: ["curl", "-ILv", "--insecure", "https://nginx","--http2"]